document.writeln(" <span id=\"jam\" > "); 
document.writeln(" <script language=\"javascript\"> "); 
document.writeln(" function jam(){ "); 
document.writeln(" var waktu = new Date(); "); 
document.writeln(" var jam = waktu.getHours(); "); 
document.writeln(" var menit = waktu.getMinutes(); "); 
document.writeln(" var detik = waktu.getSeconds(); "); 
document.writeln("   "); 
document.writeln(" if (jam < 10){ "); 
document.writeln(" jam = \"0\" + jam; "); 
document.writeln(" } "); 
document.writeln(" if (menit < 10){ "); 
document.writeln(" menit = \"0\" + menit; "); 
document.writeln(" } "); 
document.writeln(" if (detik < 10){ "); 
document.writeln(" detik = \"0\" + detik; "); 
document.writeln(" } "); 
document.writeln(" var jam_div = document.getElementById('jam'); "); 
document.writeln("   jam_div.innerHTML = jam + \":\" + menit + \":\" + detik; "); 
document.writeln(" setTimeout(\"jam()\", 1000); "); 
document.writeln(" } "); 
document.writeln(" jam(); "); 
document.writeln(" </script></span> ");
